// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NP_Encomendas_BackEnd.Context;

#nullable disable

namespace NP_Encomendas_BackEnd.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260110031739_Addresses")]
    partial class Addresses
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("NP_Encomendas_BackEnd.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Complement")
                        .HasColumnType("longtext");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("NP_Encomendas_BackEnd.Models.CartHeader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("CartHeaders");
                });

            modelBuilder.Entity("NP_Encomendas_BackEnd.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CartHeaderId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnType("longtext");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnityPrice")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("NP_Encomendas_BackEnd.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AddressId")
                        .HasColumnType("int");

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DeliverTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DeliveryMethod")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("NP_Encomendas_BackEnd.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("longtext");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnityPrice")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("NP_Encomendas_BackEnd.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Customizable")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("PromotionPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("UnitOfMeasure")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            CreateTime = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customizable = true,
                            Description = "Bolo personalizado, serve 20 fatias.",
                            ImageUrl = "/img/bolo1.jpg",
                            Name = "Bolo Temático 1 Andar",
                            Price = 150.00m,
                            UnitOfMeasure = "Unidade"
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            CreateTime = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customizable = false,
                            Description = "Brigadeiro com chocolate belga.",
                            ImageUrl = "/img/brigadeiro.jpg",
                            Name = "Cento de Brigadeiro Gourmet",
                            Price = 120.00m,
                            PromotionPrice = 110.00m,
                            UnitOfMeasure = "Cento"
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            CreateTime = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customizable = false,
                            Description = "Sabor do dia, consulte.",
                            ImageUrl = "/img/bolo_pote.jpg",
                            Name = "Bolo de Pote (Pronta Entrega)",
                            Price = 12.00m,
                            UnitOfMeasure = "Unidade"
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            CreateTime = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customizable = false,
                            Description = "Coxinhas crocantes e sequinhas.",
                            ImageUrl = "/img/coxinha.jpg",
                            Name = "Cento de Coxinha (Frango)",
                            Price = 90.00m,
                            UnitOfMeasure = "Cento"
                        },
                        new
                        {
                            Id = 5,
                            Active = true,
                            CreateTime = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customizable = false,
                            Description = "Massa podre com recheio cremoso.",
                            ImageUrl = "/img/torta_frango.jpg",
                            Name = "Torta Salgada de Frango (Kg)",
                            Price = 75.00m,
                            UnitOfMeasure = "Kg"
                        },
                        new
                        {
                            Id = 6,
                            Active = true,
                            CreateTime = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customizable = true,
                            Description = "Kit com 1 mini-bolo, 50 salgados, 20 doces.",
                            ImageUrl = "/img/kit_festa.jpg",
                            Name = "Kit Festa (10 pessoas)",
                            Price = 180.00m,
                            UnitOfMeasure = "Kit"
                        },
                        new
                        {
                            Id = 7,
                            Active = true,
                            CreateTime = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customizable = false,
                            Description = "Empadão cremoso de palmito.",
                            ImageUrl = "/img/empadao.jpg",
                            Name = "Empadão de Palmito (Kg)",
                            Price = 80.00m,
                            UnitOfMeasure = "Kg"
                        },
                        new
                        {
                            Id = 8,
                            Active = true,
                            CreateTime = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customizable = true,
                            Description = "Bordado ponto cruz personalizado com nome.",
                            ImageUrl = "/img/toalha.jpg",
                            Name = "Toalha de Mesa Bordada",
                            Price = 250.00m,
                            UnitOfMeasure = "Unidade"
                        },
                        new
                        {
                            Id = 9,
                            Active = true,
                            CreateTime = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customizable = false,
                            Description = "Vela artesanal, 200g.",
                            ImageUrl = "/img/vela.jpg",
                            Name = "Vela Aromática (Lavanda)",
                            Price = 45.00m,
                            UnitOfMeasure = "Unidade"
                        },
                        new
                        {
                            Id = 10,
                            Active = true,
                            CreateTime = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customizable = true,
                            Description = "Polvo de crochê, cores a escolher.",
                            ImageUrl = "/img/polvo.jpg",
                            Name = "Amigurumi (Polvo)",
                            Price = 90.00m,
                            UnitOfMeasure = "Unidade"
                        },
                        new
                        {
                            Id = 11,
                            Active = true,
                            CreateTime = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customizable = false,
                            Description = "Cesta completa com pães, frutas e frios.",
                            ImageUrl = "/img/cesta_cafe.jpg",
                            Name = "Cesta de Café da Manhã Standard",
                            Price = 180.00m,
                            UnitOfMeasure = "Unidade"
                        },
                        new
                        {
                            Id = 12,
                            Active = true,
                            CreateTime = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customizable = false,
                            Description = "Seleção de queijos e um vinho tinto.",
                            ImageUrl = "/img/cesta_vinho.jpg",
                            Name = "Cesta de Queijos e Vinhos",
                            Price = 260.00m,
                            UnitOfMeasure = "Unidade"
                        },
                        new
                        {
                            Id = 13,
                            Active = true,
                            CreateTime = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customizable = true,
                            Description = "Taxa de montagem. Adicione os itens avulsos no pedido.",
                            ImageUrl = "/img/cesta_vazia.jpg",
                            Name = "Monte sua Cesta (Serviço)",
                            Price = 50.00m,
                            UnitOfMeasure = "Unidade"
                        },
                        new
                        {
                            Id = 14,
                            Active = true,
                            CreateTime = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customizable = false,
                            Description = "Seleção de chocolates finos.",
                            ImageUrl = "/img/cesta_choco.jpg",
                            Name = "Cesta de Chocolates",
                            Price = 150.00m,
                            UnitOfMeasure = "Unidade"
                        },
                        new
                        {
                            Id = 15,
                            Active = true,
                            CreateTime = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customizable = false,
                            Description = "Buquê com 6 rosas.",
                            ImageUrl = "/img/buque.jpg",
                            Name = "Buquê de Rosas (Pequeno)",
                            Price = 70.00m,
                            UnitOfMeasure = "Unidade"
                        },
                        new
                        {
                            Id = 16,
                            Active = true,
                            CreateTime = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customizable = true,
                            Description = "Topo de bolo em papel lamicote. Informe nome e idade.",
                            ImageUrl = "/img/topo_bolo.jpg",
                            Name = "Topo de Bolo Personalizado",
                            Price = 35.00m,
                            UnitOfMeasure = "Unidade"
                        },
                        new
                        {
                            Id = 17,
                            Active = true,
                            CreateTime = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customizable = true,
                            Description = "Convite em papel texturizado, com laço.",
                            ImageUrl = "/img/convite.jpg",
                            Name = "Convite de Casamento (Unidade)",
                            Price = 8.50m,
                            UnitOfMeasure = "Unidade"
                        },
                        new
                        {
                            Id = 18,
                            Active = true,
                            CreateTime = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customizable = false,
                            Description = "Cartela de adesivos tema 'Planner'.",
                            ImageUrl = "/img/adesivos.jpg",
                            Name = "Kit de Adesivos (Pronta Entrega)",
                            Price = 15.00m,
                            UnitOfMeasure = "Unidade"
                        },
                        new
                        {
                            Id = 19,
                            Active = true,
                            CreateTime = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customizable = true,
                            Description = "Caderno A5 com capa dura personalizada (envie a arte).",
                            ImageUrl = "/img/caderno.jpg",
                            Name = "Caderno Personalizado (Capa)",
                            Price = 55.00m,
                            UnitOfMeasure = "Unidade"
                        });
                });

            modelBuilder.Entity("NP_Encomendas_BackEnd.Models.CartItem", b =>
                {
                    b.HasOne("NP_Encomendas_BackEnd.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("NP_Encomendas_BackEnd.Models.Order", b =>
                {
                    b.HasOne("NP_Encomendas_BackEnd.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.Navigation("Address");
                });

            modelBuilder.Entity("NP_Encomendas_BackEnd.Models.OrderItem", b =>
                {
                    b.HasOne("NP_Encomendas_BackEnd.Models.Order", null)
                        .WithMany("OrderItens")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NP_Encomendas_BackEnd.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("NP_Encomendas_BackEnd.Models.Order", b =>
                {
                    b.Navigation("OrderItens");
                });
#pragma warning restore 612, 618
        }
    }
}
