// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NP_Encomendas_BackEnd.Context;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NP_Encomendas_BackEnd.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NP_Encomendas_BackEnd.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Complement")
                        .HasColumnType("text");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("NP_Encomendas_BackEnd.Models.CartHeader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CartHeaders");
                });

            modelBuilder.Entity("NP_Encomendas_BackEnd.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CartHeaderId")
                        .HasColumnType("integer");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnityPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("NP_Encomendas_BackEnd.Models.NotificationQueue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Sent")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("NotificationQueues");
                });

            modelBuilder.Entity("NP_Encomendas_BackEnd.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AddressId")
                        .HasColumnType("integer");

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DeliverTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("DeliveryMethod")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OrderTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("NP_Encomendas_BackEnd.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnityPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("NP_Encomendas_BackEnd.Models.PaymentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateApproved")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal?>("FeeAmount")
                        .HasColumnType("numeric");

                    b.Property<int?>("Installments")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("MoneyReleaseDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal?>("NetReceivedAmount")
                        .HasColumnType("numeric");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<string>("PaymentMethodId")
                        .HasColumnType("text");

                    b.Property<string>("PaymentTypeId")
                        .HasColumnType("text");

                    b.Property<string>("PaymentUrl")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StatusDetail")
                        .HasColumnType("text");

                    b.Property<decimal?>("TransactionAmount")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("NP_Encomendas_BackEnd.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Customizable")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("UnitOfMeasure")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            CreateTime = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customizable = true,
                            Description = "Mínimo 10 de cada sabor. Sabores: Calabresa, Misto, Carne do sol, Frango c/queijo, Queijo.",
                            ImageUrl = "https://backend-api-tk7o.onrender.com/images/products/miniPizza.png",
                            Name = "Mini Pizza (10 unidades)",
                            Price = 15.00m,
                            UnitOfMeasure = "Pacote"
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            CreateTime = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customizable = true,
                            Description = "Mínimo 25 de cada sabor. Sabores: Doce de leite, Limão, Brigadeiro, M&M, Frango, Carne do sol.",
                            ImageUrl = "https://backend-api-tk7o.onrender.com/images/products/miniEmpada.png",
                            Name = "Mini Empada (25 unidades)",
                            Price = 30.00m,
                            UnitOfMeasure = "Pacote"
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            CreateTime = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customizable = true,
                            Description = "Mínimo 25 de cada sabor. Sabores: Queijo, Carne moída, Frango, Calabresa c/queijo, Misto, Carne do sol, Chocolate, Nutella, Queijo com goiaba, Banana com canela.",
                            ImageUrl = "https://backend-api-tk7o.onrender.com/images/products/miniPasteis.png",
                            Name = "Mini Pastéis (25 unidades)",
                            Price = 27.50m,
                            UnitOfMeasure = "Pacote"
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            CreateTime = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customizable = false,
                            Description = "Pavê de leite condensado, biscoito e coberto com uma ganache de chocolate. Serve de 15 a 20 pessoas.",
                            ImageUrl = "https://backend-api-tk7o.onrender.com/images/products/pave.png",
                            Name = "Travessa de Pavê",
                            Price = 70.00m,
                            UnitOfMeasure = "Unidade"
                        },
                        new
                        {
                            Id = 5,
                            Active = true,
                            CreateTime = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customizable = false,
                            Description = "Mousse com pedacinhos de abacaxi e biscoito. Serve de 15 a 20 pessoas.",
                            ImageUrl = "https://backend-api-tk7o.onrender.com/images/products/paveAbacaxi.png",
                            Name = "Pavê de Abacaxi",
                            Price = 75.00m,
                            UnitOfMeasure = "Unidade"
                        },
                        new
                        {
                            Id = 6,
                            Active = true,
                            CreateTime = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customizable = false,
                            Description = "Creme de leite condensado e doce de goiaba. Serve de 15 a 20 pessoas.",
                            ImageUrl = "https://backend-api-tk7o.onrender.com/images/products/paveLeiteGoiaba.png",
                            Name = "Pavê de Leite e Goiaba",
                            Price = 65.00m,
                            UnitOfMeasure = "Unidade"
                        },
                        new
                        {
                            Id = 7,
                            Active = true,
                            CreateTime = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customizable = true,
                            Description = "Sabores: Brigadeiro Colorido ou preto, Nutella, Tradicional.",
                            ImageUrl = "https://backend-api-tk7o.onrender.com/images/products/miniBrownie.png",
                            Name = "Mini Brownie (25 unidades)",
                            Price = 30.00m,
                            UnitOfMeasure = "Pacote"
                        },
                        new
                        {
                            Id = 8,
                            Active = true,
                            CreateTime = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customizable = true,
                            Description = "Sabores: Brigadeiro, Cenoura com chocolate, Limão com doce de leite.",
                            ImageUrl = "https://backend-api-tk7o.onrender.com/images/products/miniBolo.png",
                            Name = "Mini Bolo (20 unidades)",
                            Price = 25.00m,
                            UnitOfMeasure = "Pacote"
                        },
                        new
                        {
                            Id = 9,
                            Active = true,
                            CreateTime = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customizable = true,
                            Description = "Sabores: Goiabinha, Nutella, Gotas de chocolate, M&M.",
                            ImageUrl = "https://backend-api-tk7o.onrender.com/images/products/miniBiscoitosFesta.png",
                            Name = "Mini Biscoitos de Festa (100 unidades)",
                            Price = 50.00m,
                            UnitOfMeasure = "Cento"
                        },
                        new
                        {
                            Id = 10,
                            Active = true,
                            CreateTime = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customizable = true,
                            Description = "Serve de 10 a 15 pessoas. Opções: Torta fria de frango ou Torta fria de frango c/goiabada.",
                            ImageUrl = "https://backend-api-tk7o.onrender.com/images/products/paoAmericano.png",
                            Name = "Pão Americano",
                            Price = 80.00m,
                            UnitOfMeasure = "Unidade"
                        },
                        new
                        {
                            Id = 11,
                            Active = true,
                            CreateTime = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customizable = true,
                            Description = "Serve de 10 a 15 pessoas. Sabores: Queijo e presunto, Frango e queijo, Carne do sol e queijo.",
                            ImageUrl = "https://backend-api-tk7o.onrender.com/images/products/paoMetro.png",
                            Name = "Pão de Metro",
                            Price = 45.00m,
                            UnitOfMeasure = "Unidade"
                        },
                        new
                        {
                            Id = 12,
                            Active = true,
                            CreateTime = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customizable = true,
                            Description = "Serve de 8 a 10 pessoas. Sabores: Calabresa e queijo, Presunto e queijo, Frango e requeijão, Carne do sol e queijo.",
                            ImageUrl = "https://backend-api-tk7o.onrender.com/images/products/paoTranca.png",
                            Name = "Pão Trança",
                            Price = 45.00m,
                            UnitOfMeasure = "Unidade"
                        },
                        new
                        {
                            Id = 13,
                            Active = true,
                            CreateTime = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customizable = false,
                            Description = "Clássico pudim de leite. Serve de 15 a 20 pessoas.",
                            ImageUrl = "https://backend-api-tk7o.onrender.com/images/products/pudim.png",
                            Name = "Pudim de Leite",
                            Price = 60.00m,
                            UnitOfMeasure = "Unidade"
                        },
                        new
                        {
                            Id = 14,
                            Active = true,
                            CreateTime = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customizable = false,
                            Description = "Fundo de biscoito e um mousse de limão, coberto com chantily e raspas de limão. Serve 12 a 15 pessoas.",
                            ImageUrl = "https://backend-api-tk7o.onrender.com/images/products/tortaLimao.png",
                            Name = "Torta de Limão",
                            Price = 70.00m,
                            UnitOfMeasure = "Unidade"
                        },
                        new
                        {
                            Id = 15,
                            Active = true,
                            CreateTime = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customizable = false,
                            Description = "Fundo de biscoito de chocolate, mousse de maracujá e um delicioso mousse de chocolate. Serve 12 a 15 pessoas.",
                            ImageUrl = "https://backend-api-tk7o.onrender.com/images/products/tortaMaracujaChocolate.png",
                            Name = "Torta de Maracujá com Chocolate",
                            Price = 80.00m,
                            UnitOfMeasure = "Unidade"
                        },
                        new
                        {
                            Id = 16,
                            Active = true,
                            CreateTime = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customizable = false,
                            Description = "Empadão de frango cremoso. Serve de 15 a 20 pessoas.",
                            ImageUrl = "https://backend-api-tk7o.onrender.com/images/products/empadaoFrango.png",
                            Name = "Empadão de Frango",
                            Price = 50.00m,
                            UnitOfMeasure = "Unidade"
                        },
                        new
                        {
                            Id = 17,
                            Active = true,
                            CreateTime = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customizable = false,
                            Description = "Empadão de carne do sol e requeijão. Serve de 15 a 20 pessoas.",
                            ImageUrl = "https://backend-api-tk7o.onrender.com/images/products/empadaoCarneSol.png",
                            Name = "Empadão de Carne do Sol",
                            Price = 65.00m,
                            UnitOfMeasure = "Unidade"
                        },
                        new
                        {
                            Id = 18,
                            Active = true,
                            CreateTime = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customizable = false,
                            Description = "Empadão de camarão cremoso e requeijão. Serve de 15 a 20 pessoas.",
                            ImageUrl = "https://backend-api-tk7o.onrender.com/images/products/empadaoCamarao.png",
                            Name = "Empadão de Camarão Cremoso",
                            Price = 95.00m,
                            UnitOfMeasure = "Unidade"
                        },
                        new
                        {
                            Id = 19,
                            Active = true,
                            CreateTime = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customizable = false,
                            Description = "Pão árabe, alface, queijo, presunto e requeijão.",
                            ImageUrl = "https://backend-api-tk7o.onrender.com/images/products/miniPaoArabe.png",
                            Name = "Mini Pão Árabe (25 unidades)",
                            Price = 37.50m,
                            UnitOfMeasure = "Pacote"
                        },
                        new
                        {
                            Id = 20,
                            Active = true,
                            CreateTime = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customizable = false,
                            Description = "Pão de leite e creme de frango.",
                            ImageUrl = "https://backend-api-tk7o.onrender.com/images/products/miniGaloFrio.png",
                            Name = "Mini Galo Frio (10 unidades)",
                            Price = 20.00m,
                            UnitOfMeasure = "Pacote"
                        },
                        new
                        {
                            Id = 21,
                            Active = true,
                            CreateTime = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customizable = true,
                            Description = "Sabores: Queijo ou Misto.",
                            ImageUrl = "https://backend-api-tk7o.onrender.com/images/products/miniCroissant.png",
                            Name = "Mini Croissant (10 unidades)",
                            Price = 35.00m,
                            UnitOfMeasure = "Pacote"
                        },
                        new
                        {
                            Id = 22,
                            Active = true,
                            CreateTime = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customizable = true,
                            Description = "Mínimo de 25 de cada sabor. Sabores: Coxinha, Bolinha, Carne, Misto, Carne do sol, Pastel de carne/queijo/misto.",
                            ImageUrl = "https://backend-api-tk7o.onrender.com/images/products/centosalgado.png",
                            Name = "Cento de Salgados",
                            Price = 45.00m,
                            UnitOfMeasure = "Cento"
                        },
                        new
                        {
                            Id = 23,
                            Active = true,
                            CreateTime = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customizable = true,
                            Description = "Mínimo de 25 de cada sabor. Sabores: Misto, Queijo, Carne do sol, Frango, Pão pizza.",
                            ImageUrl = "https://backend-api-tk7o.onrender.com/images/products/salgadoforno.png",
                            Name = "Cento de Salgados de Forno",
                            Price = 55.00m,
                            UnitOfMeasure = "Cento"
                        },
                        new
                        {
                            Id = 24,
                            Active = true,
                            CreateTime = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customizable = true,
                            Description = "Sabores: Queijo, Queijo com orégano, Alho.",
                            ImageUrl = "https://backend-api-tk7o.onrender.com/images/products/centoBiscoitinhoFornoFesta.png",
                            Name = "Cento de Biscoitinho de Forno",
                            Price = 50.00m,
                            UnitOfMeasure = "Cento"
                        },
                        new
                        {
                            Id = 25,
                            Active = true,
                            CreateTime = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customizable = false,
                            Description = "Pão de leite, carne artesanal, alface, tomate, queijo, maionese e ketchup.",
                            ImageUrl = "https://backend-api-tk7o.onrender.com/images/products/miniHamburguer.png",
                            Name = "Mini Hambúrguer (10 unidades)",
                            Price = 35.00m,
                            UnitOfMeasure = "Pacote"
                        },
                        new
                        {
                            Id = 26,
                            Active = true,
                            CreateTime = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customizable = false,
                            Description = "Pão de leite, molho de tomate, batata palha, maionese e ketchup.",
                            ImageUrl = "https://backend-api-tk7o.onrender.com/images/products/miniCachorroQuente.png",
                            Name = "Mini Cachorro Quente (10 unidades)",
                            Price = 20.00m,
                            UnitOfMeasure = "Pacote"
                        },
                        new
                        {
                            Id = 27,
                            Active = true,
                            CreateTime = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customizable = true,
                            Description = "Mínimo 10 de cada sabor. Sabores: Salsicha, Queijo, Misto, Mistão, Frango, Carne do sol, Pizza, Calabresa.",
                            ImageUrl = "https://backend-api-tk7o.onrender.com/images/products/miniSalgadoForno.png",
                            Name = "Mini Salgados de Forno (10 unidades)",
                            Price = 12.50m,
                            UnitOfMeasure = "Pacote"
                        },
                        new
                        {
                            Id = 28,
                            Active = true,
                            CreateTime = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customizable = false,
                            Description = "Cheesecake com geleia de morango. Serve de 15 a 20 pessoas.",
                            ImageUrl = "https://backend-api-tk7o.onrender.com/images/products/cheesecake.png",
                            Name = "Cheesecake de Morango",
                            Price = 95.00m,
                            UnitOfMeasure = "Unidade"
                        },
                        new
                        {
                            Id = 29,
                            Active = true,
                            CreateTime = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customizable = false,
                            Description = "Guirlanda de brownie com brigadeiro e morangos. Serve de 15 a 20 pessoas.",
                            ImageUrl = "https://backend-api-tk7o.onrender.com/images/products/guirlandaBrownie.png",
                            Name = "Guirlanda de Brownie",
                            Price = 75.00m,
                            UnitOfMeasure = "Unidade"
                        },
                        new
                        {
                            Id = 30,
                            Active = true,
                            CreateTime = new DateTime(2025, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Customizable = false,
                            Description = "Fundo de biscoito, bananas, doce de leite e uma camada de chantily canela e chocolate. Serve de 15 a 20 pessoas.",
                            ImageUrl = "https://backend-api-tk7o.onrender.com/images/products/banoffee.png",
                            Name = "Banoffee",
                            Price = 80.00m,
                            UnitOfMeasure = "Unidade"
                        });
                });

            modelBuilder.Entity("NP_Encomendas_BackEnd.Models.PromotionPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FinalDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("InitialDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PromotionalPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Promotions");
                });

            modelBuilder.Entity("NP_Encomendas_BackEnd.Models.CartItem", b =>
                {
                    b.HasOne("NP_Encomendas_BackEnd.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("NP_Encomendas_BackEnd.Models.Order", b =>
                {
                    b.HasOne("NP_Encomendas_BackEnd.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.Navigation("Address");
                });

            modelBuilder.Entity("NP_Encomendas_BackEnd.Models.OrderItem", b =>
                {
                    b.HasOne("NP_Encomendas_BackEnd.Models.Order", null)
                        .WithMany("OrderItens")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NP_Encomendas_BackEnd.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("NP_Encomendas_BackEnd.Models.PaymentEntity", b =>
                {
                    b.HasOne("NP_Encomendas_BackEnd.Models.Order", "order")
                        .WithOne("Payment")
                        .HasForeignKey("NP_Encomendas_BackEnd.Models.PaymentEntity", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("order");
                });

            modelBuilder.Entity("NP_Encomendas_BackEnd.Models.PromotionPrice", b =>
                {
                    b.HasOne("NP_Encomendas_BackEnd.Models.Product", "product")
                        .WithMany("Promotions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("product");
                });

            modelBuilder.Entity("NP_Encomendas_BackEnd.Models.Order", b =>
                {
                    b.Navigation("OrderItens");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("NP_Encomendas_BackEnd.Models.Product", b =>
                {
                    b.Navigation("Promotions");
                });
#pragma warning restore 612, 618
        }
    }
}
